# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import PXREAService_pb2 as PXREAService__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class EAServiceStub(object):
    """3. 서비스를 맨 마지막에 정의

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendBytesToDevice = channel.unary_unary(
                '/PXREAService.EAService/SendBytesToDevice',
                request_serializer=PXREAService__pb2.DeviceBytesInfo.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.SendBytesToRoom = channel.unary_unary(
                '/PXREAService.EAService/SendBytesToRoom',
                request_serializer=PXREAService__pb2.RoomBytesInfo.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.WatchServerFeedback = channel.unary_stream(
                '/PXREAService.EAService/WatchServerFeedback',
                request_serializer=PXREAService__pb2.VRPid.SerializeToString,
                response_deserializer=PXREAService__pb2.ServerFeedback.FromString,
                )
        self.CancelServerFeedback = channel.unary_unary(
                '/PXREAService.EAService/CancelServerFeedback',
                request_serializer=PXREAService__pb2.VRPid.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.SendBeat = channel.unary_unary(
                '/PXREAService.EAService/SendBeat',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.DeviceControlJson = channel.unary_unary(
                '/PXREAService.EAService/DeviceControlJson',
                request_serializer=PXREAService__pb2.DeviceControlParameterJson.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class EAServiceServicer(object):
    """3. 서비스를 맨 마지막에 정의

    """

    def SendBytesToDevice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendBytesToRoom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchServerFeedback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelServerFeedback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendBeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeviceControlJson(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EAServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendBytesToDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.SendBytesToDevice,
                    request_deserializer=PXREAService__pb2.DeviceBytesInfo.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SendBytesToRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.SendBytesToRoom,
                    request_deserializer=PXREAService__pb2.RoomBytesInfo.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'WatchServerFeedback': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchServerFeedback,
                    request_deserializer=PXREAService__pb2.VRPid.FromString,
                    response_serializer=PXREAService__pb2.ServerFeedback.SerializeToString,
            ),
            'CancelServerFeedback': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelServerFeedback,
                    request_deserializer=PXREAService__pb2.VRPid.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SendBeat': grpc.unary_unary_rpc_method_handler(
                    servicer.SendBeat,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'DeviceControlJson': grpc.unary_unary_rpc_method_handler(
                    servicer.DeviceControlJson,
                    request_deserializer=PXREAService__pb2.DeviceControlParameterJson.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PXREAService.EAService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EAService(object):
    """3. 서비스를 맨 마지막에 정의

    """

    @staticmethod
    def SendBytesToDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PXREAService.EAService/SendBytesToDevice',
            PXREAService__pb2.DeviceBytesInfo.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendBytesToRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PXREAService.EAService/SendBytesToRoom',
            PXREAService__pb2.RoomBytesInfo.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WatchServerFeedback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/PXREAService.EAService/WatchServerFeedback',
            PXREAService__pb2.VRPid.SerializeToString,
            PXREAService__pb2.ServerFeedback.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CancelServerFeedback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PXREAService.EAService/CancelServerFeedback',
            PXREAService__pb2.VRPid.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendBeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PXREAService.EAService/SendBeat',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeviceControlJson(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PXREAService.EAService/DeviceControlJson',
            PXREAService__pb2.DeviceControlParameterJson.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
